### PR TITLE
feat(DSG 2578): Delete user employer

### PR DESCRIPTION
**Pull request by thechechogomez**
# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [X] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## What changes does this PR introduce?

Ticket: https://dol-ewf.atlassian.net/browse/DSG-2578

It allows an employer to delete a user from the user list. A user clicks on the delete icon on the table, a confirmation dialog opens, and if successful, then the user is deleted. 

**Pending delete user endpoint**

## Screenshot of the affected changes

https://github.com/Nuvalence/dsgov-web/assets/60438413/35ccacac-6446-4e8b-a0f8-9a41b0b9c1aa

## Checklist

- [ ] I have updated the documentation accordingly
- [X] I have confirmed all acceptance criteria defined by the story have been met
- [x] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

### CODE REVIEW

**Review by davidyoung77 — APPROVED** [review]
The code and implementation look good, I have a product question about the button text in the jira comment, I also want to confirm we double check the existing confirmation modal implementations before merging

**Review by kevincheng0 — COMMENTED** [review]
The default action of the confirmation prompt seems to be delete, though I believe the ticket specifies to make the default action to not delete the user

**Comment by thechechogomez** [comment]
> The default action of the confirmation prompt seems to be delete, though I believe the ticket specifies to make the default action to not delete the user

https://github.com/Nuvalence/dsgov-web/assets/60438413/d44a9fcd-c74f-4de8-89fc-a228b6f4bda8


@kevincheng0 This is an autofocus issue on the confirmation dialog. Removing the autofocus on the dialog, does not select the first option by default. 

> ... I also want to confirm we double check the existing confirmation modal implementations before merging

@davidyoung77 I was debating wether to make the confirmation dialog response be `primaryAction` or `seconaryAction`, would this work better than `Confirm` and `Cancel` on the dialog main actions?

**Comment by davidyoung77** [comment]
> > The default action of the confirmation prompt seems to be delete, though I believe the ticket specifies to make the default action to not delete the user
> 
>  Screen.Recording.2024-01-09.at.10.46.19.AM.mov 
> @kevincheng0 This is an autofocus issue on the confirmation dialog. Removing the autofocus on the dialog, does not select the first option by default.
> 
> > ... I also want to confirm we double check the existing confirmation modal implementations before merging
> 
> @davidyoung77 I was debating wether to make the confirmation dialog response be `primaryAction` or `seconaryAction`, would this work better than `Confirm` and `Cancel` on the dialog main actions?

This was discussed in the parking lot and we decided this is good

**Review by kevincheng0 — APPROVED** [review]

**Pull request merged**
