### PR TITLE
Dsg 2136/json editor styling

### PR DESCRIPTION
**Pull request by g8shen**
# Basics

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Styling and layout changes
- [ ] Code style changes (formatting, local variables)
- [ ] Refactoring (no functional changes)
- [ ] Build or CI related changes
- [ ] Tests
- [ ] Other... Please describe:

## Screenshot of the affected changes

Updated Json editor views compared against form.io editor:

Screenshot 2023-10-23 at 3 07 40 PM
Screenshot 2023-10-23 at 3 06 36 PM
Before:
Screenshot 2023-10-23 at 3 11 54 PM

## Checklist

- [ ] I have updated the documentation accordingly
- [ ] I have confirmed all acceptance criteria defined by the story have been met
- [ ] I have confirmed that Sonar Qube findings for new code are reviewed and fixed, or will be whitelisted

### CODE REVIEW

**Review by asultan001 — APPROVED** [review]
LGTM

**Review by kevincheng0 — APPROVED** [review]
nice

**Review by derekdiep42 — APPROVED** [review]
n i c e

**Comment by g8shen** [comment]
n  i  c  e

**Pull request merged**
